name: Daniel Warner
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33317
title: "Daniel Warner's Things"
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2c2f3c'
    - '#464a43'
    - '#987546'
    - '#9f5140'
    - '#b69149'
  brandStrength: 0.559532880783081
  lightness: 0.3959492417052388
  saturation: 0.07733393018133938
  rhythmicContrast: 0.18968603387475014
purpose: []
